In [37]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler  #standartlaştırma için eklendi
from sklearn.preprocessing import scale
from sklearn.linear_model import LinearRegression
from sklearn import model_selection 
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn import neighbors
from sklearn.svm import SVR

In [38]:
from warnings import filterwarnings
filterwarnings('ignore')

In [39]:
df=pd.read_csv(r"C:\Users\Onur\Desktop\Turkcell_Machinelearning\Hitters.csv")
df=df.dropna()
dms=pd.get_dummies(df[['League','Division','NewLeague']])

y=df["Salary"]
x_=df.drop(['Salary','League','Division','NewLeague'], axis=1).astype('float64')

x=pd.concat([x_,dms[['League_N','Division_W','NewLeague_N']]],axis=1)
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.25,random_state=42)

In [54]:
df.shape

(263, 20)

In [40]:
svr_model=SVR("linear").fit(x_train,y_train)   #rbf yazarsak doğrusal olmayan regresyon yapmış olduğumuz anlamına gelir

In [41]:
svr_model

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [42]:
svr_model.predict(x_train)[0:5]

array([219.32622169, 702.4303869 , 623.2055964 , 153.77538476,
       463.15190834])

In [43]:
svr_model.predict(x_test)[0:5]

array([679.14754685, 633.72883069, 925.68640849, 270.28463621,
       530.26659184])

In [44]:
svr_model.intercept_

array([-80.15196151])

In [45]:
svr_model.coef_

array([[ -1.21839037,   6.09602969,  -3.67574533,   0.14217075,
          0.51435919,   1.28388986,  12.55922537,  -0.08693755,
          0.46597184,   2.98259944,   0.52944523,  -0.79820799,
         -0.16015534,   0.30872794,   0.28842348,  -1.79560067,
          6.41868985, -10.74313783,   1.33374317]])

In [46]:
#modeldenklemini yazabiliriz

In [47]:
#test haatamız

In [48]:
y_pred=svr_model.predict(x_test)
np.sqrt(mean_squared_error(y_test,y_pred))

370.04084185624924

Model Tuning

In [49]:
svr_model=SVR("linear")

In [50]:
svr_model

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [52]:
svr_params={"C":[0.1,0.5,1,3]}

In [32]:
svr_cv_model=GridSearchCV(svr_model,svr_params,cv=5).fit(x_train,y_train)

In [36]:
svr_cv_model.best_params_

{'C': 0.5}

In [34]:
#fonksiyonun kaç tane işlem yaptığını kaç saniye sürdüğünü görmek için farklı bir kullanımıda vardır.

In [53]:
svr_cv_model=GridSearchCV(svr_model,svr_params,cv=5,verbose=2,n_jobs=-1).fit(x_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  20 out of  20 | elapsed:  1.5min finished


In [ ]:
#verbose 2 dersek çalışma anındaki durumu rapor ederek çalışır, njobs=-1 olunca pcdeki varolan işlemci gücü max gücünde çalışır.

In [1]:
svr_cv_model.best_params_

NameError: name 'svr_cv_model' is not defined

In [ ]:
#final modeli

In [ ]:
svr_tunned=SVR("linear",C=0.5).fit(x_train,y_train)

In [ ]:
y_pred=svr_tunned.predict(x_test)

In [ ]:
np.sqrt(mean_squared_error(y_test,y_pred))